server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://{host}:{port}/twitter_clone
    username: {username}
    password: {password}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true